#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user="mip_default"
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

postgres_ready() {
python << END
import sys
import asyncio
import asyncpg

async def main():
    con = None
    try:
        con = await asyncpg.connect(host='${POSTGRES_HOST}', port='${POSTGRES_PORT}', user='${POSTGRES_USER}', password='${POSTGRES_PASSWORD}', database='${POSTGRES_DB}')
        types = await con.fetch('SELECT * FROM pg_type')
    except Exception as e:
        print(e)
        return -1
    finally:
        if con:
            await con.close()
    return 0
sys.exit(asyncio.run(main()))

END
}
echo "Connecting to ${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
until postgres_ready; do
  >&2 echo "Waiting for PostgreSQL to become available..."
  sleep 1
done
>&2 echo "PostgreSQL is available"

exec "$@"
