name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts

      - uses: actions/checkout@v3

      - name: Use correct Docker Compose file based on branch
        if: github.ref == 'refs/heads/main'
        run: |
          cp docker-compose.prod.yml docker-compose.yml
        env:
          CI_JOB_NUMBER: 1

      - if: github.ref == 'refs/heads/main'
        name: Deploy to SSH Server (Master)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /opt/mip/fastapi.mip.institute
          SOURCE: ./  # The source directory in your repository
          ARGS: "-rlgoDzvc -i"  # Rsync arguments
          EXCLUDE: "/node_modules/, /dist/"  # Optional: exclude certain directories

      - if: github.ref == 'refs/heads/develop'
        name: Deploy to SSH Server (Dev)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /opt/mip/fastapi.mip.institute
          SOURCE: ./  # The source directory in your repository
          ARGS: "-rlgoDzvc -i"  # Rsync arguments
          EXCLUDE: "/node_modules/, /dist/"  # Optional: exclude certain directories

      - name: Clean up Docker Compose file
        run: rm docker-compose.yml
