name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CONTAINER_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }} .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: "${{ secrets.SERVER_SSH_KEY }}"
        port: 22
        script: |
          docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
          docker-compose -f /opt/pmnts/fa-payments/docker-compose.${{ github.ref_name }}.yml down
          docker-compose -f /opt/pmnts/fa-payments/docker-compose.${{ github.ref_name }}.yml up -d
